// const express = require('express')
// const Controller = require('../controllers/controller')
// const bolabio = express.Router()

// bolabio.get("/", Controller.showAllBio)
// bolabio.get("/add", Controller.addBio)
// bolabio.get("/search", Controller.search)
// bolabio.get("/:id", Controller.detail)
// bolabio.post("/add", Controller.postAddBio)
// bolabio.post("/:id/edit", Controller.editBio)
// bolabio.get("/:id/delete", Controller.delete)